eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
    registerWithEureka: true
    fetchRegistry: true
    instance:
        preferIpAddress: true
#
server:
    port: 0
#
spring:
    application:
        name: testService
# Spring Boot Admin Client URL
    boot:
      admin:
        client:
          url: http://localhost:8761/admin/
#
info:
  app:
    description: Test Service
    name: testService
    version: 1.0.0
  java:
    version: ${java.specification.version}
management:
  endpoints:
    web:
      exposure:
        exclude: flyway,liquibase
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  info:
    git:
      mode: full
